version: '3.8'

services:
  fastapi-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: firmable-backend
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - API_SECRET_KEY=${API_SECRET_KEY}
      - UNSTRUCTURED_API_KEY=${UNSTRUCTURED_API_KEY}
      - PORT=8000
    env_file:
      - .env.local
    volumes:
      # Mount for development (hot reload)
      - ./api:/app/api
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s

networks:
  default:
    name: firmable-network
