providers = ["python"]

[phases.setup]
nixPkgs = ["python310"]
nixLibs = ["gcc"]

[phases.install]
cmds = [
  "pip install --upgrade pip",
  "pip install -r requirements.txt"
]

[start]
cmd = "uvicorn api.index:app --host 0.0.0.0 --port $PORT"
